# Generated by Django 4.2.3 on 2023-07-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_code',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
